server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true
grpc:
  client:
    product-server:
      address: 'static://0.0.0.0:3335'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    user-server:
      address: 'static://0.0.0.0:3334'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    calculator-server:
      address: 'static://0.0.0.0:3336'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
---
spring:
  profiles: prod
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true
grpc:
  client:
    product-server:
      address: 'static://product:3335'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    user-server:
      address: 'static://user:3334'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    calculator-server:
      address: 'static://calculator:3336'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext